version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "19915:3000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mydb

volumes:
  db_data:
