version: '3'
services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "19915:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
      